- hosts: all
  become: yes
  become_method: sudo
  tasks: 

    - name: install java on slave
      script: java.sh

    - name: install docker 
      script: docker.sh


- hosts: localhost
  connection: local
  tasks: 

    - name: install java on master
      script: java.sh


    - name: install jenkis on master
      script: jenkins.sh



        
