- hosts: all
  become: yes
  become_method: sudo
  
  tasks: 

    - name: Copy DB script to server
      copy:
        src: .
        dest: /home/ubuntu
        owner: root
        group: root        
        mode: 654
      when: "'slave' in inventory_hostname"

    - name: install java on slave
      shell: /home/ubuntu/java.sh
      args:
        executable: /bin/bash
      when: "'slave' in inventory_hostname"

    - name: install java on slave
      shell: /home/ubuntu/inteli_lab/java.sh
      args:
        executable: /bin/bash
      when: "'master' in inventory_hostname"


    - name: install docker 
      shell: /home/ubuntu/docker.sh
      args:
        executable: /bin/bash
      when: "'slave' in inventory_hostname"

    - name: install jenkins
      shell: /home/ubuntu/inteli_lab/jenkins.sh
      args:
        executable: /bin/bash
      when: "'master' in inventory_hostname"









        
